name: Theme Library Generate

on: workflow_dispatch

concurrency: 
  group: release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show directory names
        run: |
          ls -1

      - name: Show directory names
        run: |
          cat "Analogue-Arimo/credits.txt"

      - name: Create temporary file
        run: |
          echo preview > "preview/credits.txt"

      - name: Show directory names
        run: |
          cat "preview/credits.txt"
          
      - name: Generate text file with all directory names, with directory name inside
        run: |
          mkdir -p /tmp/page && for dir in */; do dir_name="${dir%/}"; (cd "${dir_name}" && echo "| ![${dir_name}](<https://raw.githubusercontent.com/MustardOS/theme/main/preview/${dir_name}.png>) <br>[${dir_name}]" > "/tmp/page/${dir_name}.txt" && echo -n "(https://github.com/MustardOS/theme/releases/download/YEAR-DATE-TIME/${dir_name}.zip)<br><sup>" | tr [:space:] "." >> "/tmp/page/${dir_name}.txt"); cat "${dir_name}/credits.txt" >> "/tmp/page/${dir_name}.txt"; (cd "${dir_name}" && echo "</sup>" >> "/tmp/page/${dir_name}.txt"); done

#  && cat "${dir_name}/credits.txt >> "/tmp/page/${dir_name}.txt"
#| ![$dir_name](https://raw.githubusercontent.com/MustardOS/theme/main/preview/$dir_name.png) <br>[$dir_name]
#(https://github.com/MustardOS/theme/releases/download/2024-05-31_1018/Analogue-Arimo.zip) <br><sup>by: Cheema OTB (original: Aemiii91)</sup> 

      - name: Ensure all line breaks are now deleted
        run: |
          for dir in */; do dir_name="${dir%/}"; echo "e" >> "/tmp/page/${dir_name}.txt"; done
          
      - name: Replace line breaks with space
        run: |
          mkdir -p /tmp/txt && for dir in */; do dir_name="${dir%/}"; tr "\n" " " < "/tmp/page/${dir_name}.txt" > "/tmp/txt/${dir_name}.txt"; done

      - name: See if this worked?
        run: |
          cat "/tmp/page/muOS - Classic.txt"

      - name: See if this worked?
        run: |
          cat "/tmp/txt/muOS - Classic.txt"

      - name: Ensure all line breaks are now deleted
        run: |
          for dir in */; do dir_name="${dir%/}"; tr "\n" " " < "/tmp/txt/${dir_name}.txt" > "/tmp/page/${dir_name}.txt"; done

      - name: Delete preview text file
        run: |
          rm /tmp/page/preview.txt

      - name: Delete preview text file
        run: |
          rm /tmp/txt/preview.txt

      - name: Show directory names
        run: |
          ls -1 /tmp/page

      - name: See if this worked?
        run: |
          more "/tmp/page/Retro Glow Blue.txt"

      - name: See if this worked?
        run: |
          more "/tmp/page/muOS - Classic.txt"

      - name: See if this worked?
        run: |
          more "/tmp/txt/Retro Glow Blue.txt"

      - name: See if this worked?
        run: |
          more "/tmp/txt/muOS - Classic.txt"

#echo "Welcome GFG" > output.txt
#This will write the output of the echo command to the file name `output.txt`. File will be overwritten if it already exists.
#If we want to append the output in an existing file, we use `>>` instead of `>`.
          
# for dir in */; do dir_name="${dir%/}";

# ${dir_name} <- take all spaces and convert to .
# echo "${dir_name}" | tr \ \ .
# echo "${dir_name}" | tr [:space:] []

# https://github.com/MustardOS/theme/releases/download/${{steps.date.outputs.date}}/Analogue-Arimo.zip
