name: Theme Table and Scripts Generate

on: workflow_dispatch

concurrency: 
  group: release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create temporary credits file
        run: |
          echo preview > "preview/credits.txt"
          
      - name: Generate text file with all directory names, with directory name inside
        run: |
          mkdir -p /tmp/page && for dir in */; do dir_name="${dir%/}"; (cd "${dir_name}" && echo "| ![${dir_name}](<https://raw.githubusercontent.com/MustardOS/theme/main/preview/${dir_name}.png>) <br>[${dir_name}" > "/tmp/page/${dir_name}.txt" && echo -n "](https://github.com/MustardOS/theme/releases/latest/download/${dir_name}.zip)<br><sup>" | tr [:space:] "." >> "/tmp/page/${dir_name}.txt"); cat "${dir_name}/credits.txt" >> "/tmp/page/${dir_name}.txt"; (cd "${dir_name}" && echo "</sup>" >> "/tmp/page/${dir_name}.txt"); done
       
      - name: Replace line breaks with space
        run: |
          mkdir -p /tmp/txt && for dir in */; do dir_name="${dir%/}"; tr "\n" " " < "/tmp/page/${dir_name}.txt" > "/tmp/txt/${dir_name}.txt"; done

      - name: Ensure all line breaks are now deleted
        run: |
          for dir in */; do dir_name="${dir%/}"; tr -d "\n\r" < "/tmp/txt/${dir_name}.txt" > "/tmp/page/${dir_name}.txt"; done

      - name: Delete placeholder preview text file
        run: |
          rm /tmp/page/preview.txt

      - name: Delete placeholder preview text file
        run: |
          rm /tmp/txt/preview.txt

      - name: make all file names uppercase
        run: |
          cd /tmp/page && for f in *; do mv -- "$f" "$(tr [:lower:] [:upper:] <<< "$f")" ; done

      - name: Add enter at end of every file
        run: |
          for file in /tmp/page/*; do sed -i -e '$a\' "$file"; done
          
      - name: Combine the files
        run: |
          cat /tmp/page/* > /tmp/page/complet.txt

      - name: Format into three per line
        run: |
          paste -d ' ' - - - < /tmp/page/complet.txt > /tmp/page/complete.txt

      - name: Delete placeholder text file
        run: |
          rm /tmp/page/complet.txt

      - name: Delete old theme site
        run: |
          rm themesite.md

      - name: Delete old README
        run: |
          rm README.md
          
      - name: Insert | at end of every line
        run: |
          sed -i "s/$/ |/" /tmp/page/complete.txt
          
      - name: Test to see if this has worked
        run: |
          more "/tmp/page/complete.txt"    

      - name: Merge with the theme template
        run: |
          cat ".github/md_templates/themepagetemplate.md" /tmp/page/complete.txt > /tmp/themesite.md

      - name: Merge with the readme template
        run: |
          cat ".github/md_templates/readmetemplate.md" /tmp/page/complete.txt > /tmp/readme.md

      - name: See if this worked?
        run: |
          more "/tmp/themesite.md" 

      - name: See if this worked?
        run: |
          more "/tmp/readme.md" 

      - name: Move file to correct location
        run: |
          cp "/tmp/themesite.md" "themesite.md"

      - name: Move file to correct location
        run: |
          cp "/tmp/readme.md" "README.md"
          
      - name: Create individual script files for on-device theme downloader
        run: |
          mkdir -p /tmp/scripts && for dir in */; do dir_name="${dir%/}"; (cd "${dir_name}" && echo -e -n "#!/bin/sh \n \nURL=" > "/tmp/scripts/${dir_name}.sh" && echo -e -n "\"https://github.com/MustardOS/theme/releases/latest/download/${dir_name}.zip\"" | sed 's/ & /./g' | tr [:space:] "." >> "/tmp/scripts/${dir_name}.sh"); (cd "${dir_name}" && echo -e -n "\nTHEME_NAME=\"${dir_name}\"\nLOCAL_ZIP_PATH=\"/mnt/mmc/MUOS/theme/${dir_name}.zip\"\nLOCAL_PREVIEW=\"/mnt/mmc/MUOS/theme/preview/${dir_name}.png\"\nARCHIVE_ZIP=\"/mnt/mmc/ARCHIVE/${dir_name}.zip\"\nSH_NAME=\"${dir_name}.sh\"\n" >> "/tmp/scripts/${dir_name}.sh" && echo -e -n "PREVIEW=\"https://raw.githubusercontent.com/MustardOS/theme/main/preview/${dir_name}.png\"\nCREDITS_INFO=\"" | sed 's/ /%20/g' >> "/tmp/scripts/${dir_name}.sh"); cat "${dir_name}/credits.txt" | tr -d "\n\r" >> "/tmp/scripts/${dir_name}.sh"; (cd "${dir_name}" && echo -e "\" \n \nrm -rf \"\$MUX_TEMP\" /tmp/muxlog_* \n \n. \"/mnt/mmc/MUOS/application/.ThemeDownloader/scripts/ThemeInstall.sh\" \n " >> "/tmp/scripts/${dir_name}.sh"); done
       
      - name: Remove preview file
        run: |
          rm "/tmp/scripts/preview.sh"
          
      - name: Push scripts to the secret folder
        run: |
          (shopt -s dotglob; cp /tmp/scripts/* ".github/.ThemeDownloader/themes/")

      - name: Delete placeholder credits file
        run: |
          rm preview/credits.txt

      - name: Create complete theme list as txt
        run: |
          (shopt -s dotglob; rm ".github/.ThemeDownloader/scripts/complete.txt") 
          (shopt -s dotglob; touch ".github/.ThemeDownloader/scripts/complete.txt")
          (shopt -s dotglob; for dir in */; do dir_name="${dir%/}"; echo "${dir_name}" >> ".github/.ThemeDownloader/scripts/complete.txt"; done)

      - name: Edit this list to remove non-theme folders
        run: |
          (shopt -s dotglob; sed -i.bak '/.git/d' ".github/.ThemeDownloader/scripts/complete.txt")
          (shopt -s dotglob; sed -i.bak '/.github/d' ".github/.ThemeDownloader/scripts/complete.txt")
          (shopt -s dotglob; sed -i.bak '/preview/d' ".github/.ThemeDownloader/scripts/complete.txt")

      - name: Push files to the github, replacing the previous
        run: |
          git config --global user.name "VagueParade"
          git config --global user.email "166325657+VagueParade@users.noreply.github.com"

          git add -A
          git commit -m "Action with generated files"
          git push
          
