name: README Edit

on: workflow_dispatch

concurrency: 
  group: release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update README.md
        run: |
          sed -i 's/<releasetable>/'/preview/Analogue-Arimo.png'/' README.md
          git config user.email "VagueParade@users.noreply.github.com"
          git config user.name "VagueParade"
          git commit -am "Automated report"
          git push
